site_name: Huang FTS427's Website
site_url: https://www.fts427.top/
repo_url: https://github.com/FTS427/FTS427.github.io
repo_name: FTS427/FTS427.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - 2024 Huang FTS427
theme:
  custom_dir: overrides
  name: material
  language: zh
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
  icon: 
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  favicon: assets/favicon.png
  logo: assets/favicon.png
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
  extra:
plugins: 
  - search
  - blog
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - 欢迎！: index.md
  - 关于我: about_me.md
  - 感谢列表: thx.md
  - 我的服务器: 
    - ZH-Server: Minecraft/ZHS.md
    - Zn-Server（已关闭）: Minecraft/ZnS.md
    - 服务器所包含资源: Minecraft/resource.md
    - 服务器贡献人员: Minecraft/gaming_thx.md
    - 游戏环境基础原则: Minecraft/gamimg_env.md
    - 管理员注意事项: Minecraft/op_rules.md
    - 游戏黑名单: Minecraft/no_play.md
  - 友链: links.md
  - 小记: blog/index.md
  - 技术文档: 
    - 前言: tech-docs/index.md
    - Archlinux相关: 
      - Archlinux酱: tech-docs/archlinux/archlinux_info.md
      - Archlinux安装: tech-docs/archlinux/archlinux_install.md
    - Android相关: 
      - 前言: tech-docs/android/index.md
      - Lenovo TB-X306FC_PRC: 
        - 设备信息: tech-docs/android/lenovo/device_info.md
        - 解 BL 锁: tech-docs/android/lenovo/unlock_bl.md
        - 解 BL 锁后干点啥: tech-docs/android/lenovo/after_unlockbl.md
        - 刷系统: tech-docs/android/lenovo/flash_system.md
      - OPPO A31t: 
        - 设备信息: tech-docs/android/oppo/device_info.md
        - 刷机: tech-docs/android/oppo/flash_system.md
    - 其它工具: 
      - MKdocs 网站框架: tech-docs/tools/mkdocs.md
      - Scoop 包管理器: tech-docs/tools/scoop_use.md
      - LL_Easier 快速打包 LeviLamina: tech-docs/tools/ll_easier.md
