site_name: Huang FTS427's Website
site_url: https://www.fts427.top/
repo_url: https://github.com/FTS427/FTS427.github.io
repo_name: FTS427/FTS427.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - 2025 Huang FTS427
theme:
  custom_dir: overrides
  name: material
  language: zh
  features:
    - content.action.edit
    - content.code.annotate
    - content.action.copy
    - content.action.select
    - search.suggest
    - search.highlight
    - navigation.tabs
    - header.autohide
  icon: 
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  favicon: assets/favicon.png
  logo: assets/favicon.png
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Light mode

plugins: 
  - search
  - blog:
      authors_file: "{blog}/.authors.yml"
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets

nav:
  - 欢迎！: index.md
  - 关于我: about_me.md
  - 感谢列表: thx.md
  - Minecraft 服务器: 
    - ZH-Server: Minecraft/ZHS.md
    - Zn-Server（已终结）: Minecraft/ZnS.md
    - 服务器贡献人员: Minecraft/gaming_thx.md
    - 游戏环境基础原则: Minecraft/gamimg_env.md
    - 管理员注意事项: Minecraft/op_rules.md
    - ZH-Server 资源: Minecraft/ZHS_resource.md
    - 游戏黑名单: Minecraft/no_play.md
  - 友链: links.md
  - 小记: 
    - blog/index.md
  - 技术文档: 
    - 前言: tech-docs/index.md
    - Archlinux 相关: 
      - Archlinux 酱: tech-docs/archlinux/archlinux_info.md
      - Archlinux 安装: tech-docs/archlinux/archlinux_install.md
    - Android相关: 
      - 前言: tech-docs/android/index.md
      - Lenovo TB-X306FC_PRC: 
        - 设备信息: tech-docs/android/lenovo/device_info.md
        - 刷机资源: tech-docs/android/lenovo/resource.md
        - 解 BL 锁: tech-docs/android/lenovo/unlock_bl.md
        - 解 BL 锁后干点啥: tech-docs/android/lenovo/after_unlockbl.md
        - 刷 GSI 系统: tech-docs/android/lenovo/flash_gsi_system.md
        - 刷系统: tech-docs/android/lenovo/flash_stock_system.md
        - 让我们编译: 
          - tech-docs/android/lenovo/build_rom/index.md
          - 编译 Lineage OS: tech-docs/android/lenovo/build_rom/lineage_build.md
      - OPPO A31t: 
        - 设备信息: tech-docs/android/oppo/device_info.md
        - 刷机: tech-docs/android/oppo/flash_system.md
      - Waydroid:
        - BA 折腾记: tech-docs/android/waydroid/blue_archive.md
    - 其它工具: 
      - MKdocs 网站框架: tech-docs/tools/mkdocs.md
      - Scoop 包管理器: tech-docs/tools/scoop_use.md
      - LL_Easier 快速打包 LeviLamina: tech-docs/tools/ll_easier.md
