site_name: Huang FTS427's Website
repo_url: https://github.com/FTS427/FTS427.github.io
repo_name: FTS427/FTS427.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - 2024 Huang FTS427
theme:
  name: material
  language: zh
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
  icon: 
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  palette:
    # Light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode

  extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FTS427

plugins: 
  - search
  - blog

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
