site_name: Huang FTS427's Website
repo_url: https://github.com/FTS427/FTS427.github.io
repo_name: FTS427/FTS427.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - 2024 Huang FTS427
theme:
  name: material
  language: zh
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
  icon: 
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  favicon: assets/favicon.png
  logo: assets/favicon.png
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
  extra:
plugins: 
  - search
  - blog

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - 欢迎！: index.md
  - 关于我: about_me.md
  - 感谢列表: thx.md
  - 我的服务器: 
    - ZH-Server: Minecraft/ZHS.md
    - Zn-Server: Minecraft/ZHS-F.md
    - ZH-Server资源: Minecraft/resource_zh.md
    - 服务器贡献人员: Minecraft/gaming_thx.md
    - 游戏环境基础原则: Minecraft/gamimg_env.md
    - 管理员注意事项: Minecraft/op_rules.md
    - 黑名单: Minecraft/no_play.md
  - 友链: links.md
  - 小记: 
    - 引入: blog/index.md
  - 技术性文档: 
    - 前言: tech-docs/index.md
    - Archlinux相关: 
      - Archlinux酱: tech-docs/archlinux/archlinux_info.md
      - Archlinux安装: tech-docs/archlinux/archlinux_install.md
    - Android相关:
      - TB-X306FC_PRC:
        - 设备简介: tech-docs/android/lenovo/device_info.md
        - 解锁BL: tech-docs/android/lenovo/unlock_bl.md
        - 结完BL后干点啥: tech-docs/android/lenovo/after_unlockbl.md
        - 刷系统: tech-docs/android/lenovo/flash_system.md
    - 其它工具: 
      - MKdocs网站框架: tech-docs/tools/mkdocs.md
      - Scoop包管理器: tech-docs/tools/scoop_use.md
